apiVersion: 1
datasources:
  - name: PostgreSQL
    uid: github_events_db
    type: postgres
    url: timescaledb:5432
    database: github_events
    user: github
    secureJsonData:
      password: github_secret
    jsonData:
      sslmode: 'disable'
      postgresVersion: 16
      timescaledb: true
    editable: true