{
 "title": "pm4",
 "time": { "from": "now-5y", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of Events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "github_events", "rawSql": "SELECT count(*) FROM events;" }
   ]
  },
  {
   "title": "Number of Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "github_events", "rawSql": "SELECT count(*) FROM users;" }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "github_events",
     "rawSql": "SELECT \n    CASE \n        WHEN lat IS NOT NULL THEN 'Geocoded' \n        ELSE 'No Geodata' \n    END AS category,\n    COUNT(*) AS count\nFROM users\nWHERE is_bot = FALSE\nGROUP BY 1;"
    }
   ]
  },
  {
   "title": "Number of Repos",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "github_events", "rawSql": "SELECT count(*) FROM repos;" }
   ]
  },
  {
   "title": "Location of geocoded users",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "github_events",
     "rawSql": "SELECT \n  lat, \n  lng, \n  country,\n  count(*) as \"Event Count\"\nFROM users\nJOIN events ON users.username = events.actor_username\nWHERE $__timeFilter(events.time)\nAND lat IS NOT NULL\nGROUP BY lat, lng, country;"
    }
   ]
  }
 ]
}